name: Build and Deploy to Pages
"on":
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true

# inputs:
#   node-version:
#     description: "The version of Node.js"
#     required: true
#     default: "18.x"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/configure-pages@v1
        id: pages

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
